# Generated by Django 4.2.16 on 2024-10-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terms_and_study_groups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("date_from", models.DateField(unique=True)),
                ("date_to", models.DateField(unique=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["date_from"],
            },
        ),
        migrations.AddConstraint(
            model_name="term",
            constraint=models.UniqueConstraint(
                fields=("date_from", "date_to"), name="unique_term_dates"
            ),
        ),
    ]
