# Generated by Django 4.2.16 on 2024-10-25 04:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dictionaries", "0002_subject_term_term_unique_term_dates"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                (
                    "order_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionaries.studygroup",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionaries.subject",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionaries.term",
                    ),
                ),
            ],
            options={
                "ordering": ["term", "study_group", "weekday", "order_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="scheduletemplate",
            constraint=models.UniqueConstraint(
                fields=("term", "study_group", "weekday", "order_number"),
                name="unique_schedule_template_row",
            ),
        ),
    ]
