# Generated by Django 4.2.16 on 2024-10-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionaries", "0003_scheduletemplate_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="scheduletemplate",
            index=models.Index(
                fields=["term", "study_group"], name="term_study_group_idx"
            ),
        ),
    ]
