# Generated by Django 4.2.16 on 2024-10-29 11:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dictionaries", "0004_scheduletemplate_term_study_group_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "order_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("homework", models.TextField(blank=True)),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionaries.studygroup",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionaries.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["study_group", "date", "order_number"],
                "indexes": [
                    models.Index(
                        fields=["study_group", "date"], name="study_group_date_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.UniqueConstraint(
                fields=("study_group", "date", "order_number"),
                name="unique_schedule_row",
            ),
        ),
    ]
