# Generated by Django 4.2.16 on 2024-10-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionaries", "0005_schedule_schedule_unique_schedule_row"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="date",
            field=models.DateField(),
        ),
    ]
